"""Architecture insight services.

Every capability has a deterministic fallback so the platform remains fully
functional (including Hebrew output) when no AI provider is reachable.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from app.ai import prompts
from app.ai.provider import AIProvider, AIProviderError
from app.diagrams.base import DiagramFilters
from app.graph.model import KnowledgeGraph, NodeKind

log = logging.getLogger("aai.insights")

T: dict[str, dict[str, str]] = {
    "en": {
        "purpose_class": "Shows the type structure and relationships of the analysed code.",
        "purpose_architecture": "Shows the runtime structure of the system and how its parts collaborate.",
        "purpose_component": "Shows components, their interfaces and boundaries.",
        "purpose_sequence": "Shows the order of interactions for a representative flow.",
        "purpose_dataflow": "Shows how data enters, is processed by, and is stored in the system.",
        "purpose_deployment": "Shows how the system is packaged and deployed.",
        "purpose_dependency": "Shows dependencies between modules and highlights cycles.",
        "purpose_database": "Shows the persistent data model and its relationships.",
        "purpose_state": "Shows the lifecycle states of a key domain concept.",
        "described": "The diagram contains {nodes} elements and {edges} relationships.",
        "generated_offline": "Generated by static analysis (no AI provider configured).",
        "no_issue": "No structural issues were detected by static analysis.",
        "risk_cycle": "Circular dependency between {modules}.",
        "risk_god": "{name} is very large ({methods} methods) and likely has too many responsibilities.",
        "risk_layer": "{src} ({src_layer}) depends on {dst} ({dst_layer}), which inverts the intended layering.",
        "risk_hub": "{name} is connected to {degree} other elements and is a change hotspot.",
        # Severity, effort and impact are shown as words rather than a bare
        # colour, and every risk carries the reasoning behind it.
        "severity_high": "High",
        "severity_medium": "Medium",
        "severity_low": "Low",
        "effort_small": "Small - a focused change in one or two files",
        "effort_medium": "Medium - a contained refactor with tests",
        "effort_large": "Large - stage it over several commits",
        "effort_none": "No action required",
        "impact_coupling": "Coupling and change propagation",
        "impact_maintainability": "Maintainability and testability",
        "impact_layering": "Dependency direction and layering",
        "impact_change_risk": "Change risk and blast radius",
        "impact_none": "Nothing to address",
        "risk_cycle_title": "Circular dependency between modules",
        "risk_cycle_why": "Modules inside a cycle cannot be built, tested, released or "
        "understood on their own. A change to any member can propagate all the way back "
        "to itself, and none of them can be extracted or reused independently.",
        "risk_cycle_fix": "Identify the single dependency that closes the loop and invert it. "
        "Move the type both sides share into a neutral module, or declare the contract in the "
        "lower-level module and let the higher-level one implement it.",
        "risk_god_title": "Oversized type carrying too many responsibilities",
        "risk_god_why": "A type this large is hard to test in isolation, tends to be edited by "
        "several people at once, and forces every consumer to depend on far more behaviour than "
        "it actually uses. Its size is usually a symptom of unrelated responsibilities living "
        "in the same file.",
        "risk_god_fix": "Group the methods by the data they touch. Each group that shares state "
        "is a candidate for its own class. Extract the largest group first, keep the original "
        "type as a thin facade so callers keep working, then move callers over gradually.",
        "risk_layer_title": "Dependency pointing the wrong way through the layers",
        "risk_layer_why": "A lower layer reaching into a higher one destroys the property that "
        "makes layering useful: you can no longer replace, test or deploy the lower layer "
        "without dragging the upper layer along with it.",
        "risk_layer_fix": "Define the interface the lower layer needs inside the lower layer, "
        "and have the higher layer implement it. The call still happens at runtime, but the "
        "compile-time dependency now points inwards.",
        "risk_hub_title": "Highly connected element",
        "risk_hub_why": "Everything that touches this element risks breaking its many neighbours, "
        "so it attracts merge conflicts and regressions. High connectivity is not wrong by "
        "itself, but it makes this element the most expensive place in the codebase to change.",
        "risk_hub_fix": "Check whether the connections are of one kind or several. If several, "
        "split them by concern. If one, put a narrow interface in front of it so its neighbours "
        "depend on the contract rather than the implementation.",
        "no_issue_title": "No structural issues detected",
        "no_issue_why": "Static analysis found no dependency cycles, layering violations or "
        "oversized types in the elements shown on this diagram.",
        "no_issue_fix": "Keep the current boundaries and re-run the analysis after larger "
        "changes so regressions are caught early.",
        "evidence_cycle_len": "{length} modules take part in the cycle",
        "evidence_cycle_path": "Cycle path: {path}",
        "evidence_god_methods": "{methods} methods",
        "evidence_god_props": "{properties} fields or properties",
        "evidence_god_deps": "{dependencies} outgoing dependencies",
        "evidence_hub_degree": "{degree} incoming and outgoing relationships",
        "evidence_layer_edge": "Relationship of kind '{kind}' from {src} to {dst}",
        "evidence_file": "Declared in {file}",
        "improve_cycle": "Break cycles by extracting shared abstractions into a neutral module.",
        "improve_god": "Split large classes along their responsibilities and introduce focused services.",
        "improve_layer": "Introduce interfaces so lower layers do not reference higher layers.",
        "improve_abstraction": "Add interfaces at module boundaries to enable substitution and testing.",
        "improve_docs": "Document the responsibility of each component in the repository.",
        "strength_layers": "Clear separation into {count} architectural layers.",
        "strength_abstraction": "Healthy use of interfaces (abstraction ratio {ratio}).",
        "strength_nocycle": "No circular dependencies between modules.",
        "strength_tests": "A dedicated test area exists in the repository.",
        "strength_containers": "Deployment is described declaratively ({count} workloads).",
        "summary": "The system contains {components} components and {types} types across {languages}. Static analysis scored the architecture {score}/100 (grade {grade}).",
    },
    "he": {
        "purpose_class": "מציג את מבנה הטיפוסים והקשרים בין המחלקות בקוד.",
        "purpose_architecture": "מציג את מבנה המערכת בזמן ריצה ואת אופן שיתוף הפעולה בין חלקיה.",
        "purpose_component": "מציג רכיבים, הממשקים שהם מספקים והגבולות ביניהם.",
        "purpose_sequence": "מציג את סדר האינטראקציות עבור זרימה מייצגת.",
        "purpose_dataflow": "מציג כיצד נתונים נכנסים למערכת, מעובדים ונשמרים.",
        "purpose_deployment": "מציג כיצד המערכת נארזת ונפרסת.",
        "purpose_dependency": "מציג תלויות בין מודולים ומדגיש מעגלי תלות.",
        "purpose_database": "מציג את מודל הנתונים המתמיד ואת הקשרים בין הטבלאות.",
        "purpose_state": "מציג את מצבי מחזור החיים של מושג מרכזי בדומיין.",
        "described": "התרשים כולל {nodes} רכיבים ו־{edges} קשרים.",
        "generated_offline": "נוצר על ידי ניתוח סטטי (לא הוגדר ספק AI).",
        "no_issue": "ניתוח סטטי לא מצא בעיות מבניות.",
        "risk_cycle": "תלות מעגלית בין {modules}.",
        "risk_god": "{name} גדולה מאוד ({methods} מתודות) וקרוב לוודאי מרכזת יותר מדי אחריות.",
        "risk_layer": "{src} ({src_layer}) תלוי ב־{dst} ({dst_layer}), בניגוד לכיוון השכבות הרצוי.",
        "risk_hub": "{name} מחובר ל־{degree} רכיבים אחרים ומהווה מוקד שינויים.",
        "severity_high": "גבוהה",
        "severity_medium": "בינונית",
        "severity_low": "נמוכה",
        "effort_small": "קטן - שינוי ממוקד בקובץ אחד או שניים",
        "effort_medium": "בינוני - ריפקטור מוגבל בליווי בדיקות",
        "effort_large": "גדול - כדאי לפרוס על פני מספר קומיטים",
        "effort_none": "לא נדרשת פעולה",
        "impact_coupling": "צימוד והתפשטות שינויים",
        "impact_maintainability": "תחזוקתיות ויכולת בדיקה",
        "impact_layering": "כיוון התלויות והשכבות",
        "impact_change_risk": "סיכון בשינוי והיקף ההשפעה",
        "impact_none": "אין מה לתקן",
        "risk_cycle_title": "תלות מעגלית בין מודולים",
        "risk_cycle_why": "מודולים בתוך מעגל תלות אינם ניתנים לבנייה, לבדיקה, לשחרור או "
        "להבנה בנפרד. שינוי באחד מהם עלול לחזור אליו עצמו דרך המעגל, ואף אחד מהם לא ניתן "
        "לחילוץ או לשימוש חוזר בפני עצמו.",
        "risk_cycle_fix": "יש לאתר את התלות היחידה שסוגרת את המעגל ולהפוך את כיוונה. "
        "אפשר להעביר את הטיפוס המשותף למודול ניטרלי, או להגדיר את החוזה במודול הנמוך "
        "ולתת למודול הגבוה לממש אותו.",
        "risk_god_title": "טיפוס מנופח שמרכז יותר מדי אחריות",
        "risk_god_why": "טיפוס בגודל כזה קשה לבדיקה בבידוד, נערך במקביל על ידי כמה אנשים, "
        "ומאלץ כל צרכן שלו להיות תלוי בהרבה יותר התנהגות ממה שהוא באמת צריך. הגודל הוא "
        "בדרך כלל סימפטום לכך שאחריות שאינה קשורה זו לזו יושבת באותו קובץ.",
        "risk_god_fix": "יש לקבץ את המתודות לפי הנתונים שהן נוגעות בהם. כל קבוצה שחולקת "
        "מצב היא מועמדת למחלקה נפרדת. מחלצים תחילה את הקבוצה הגדולה ביותר, משאירים את "
        "הטיפוס המקורי כחזית דקה כדי שהקוראים ימשיכו לעבוד, ומעבירים אותם בהדרגה.",
        "risk_layer_title": "תלות בכיוון הפוך בין השכבות",
        "risk_layer_why": "שכבה נמוכה שפונה לשכבה גבוהה מבטלת את היתרון המרכזי של חלוקה "
        "לשכבות: כבר אי אפשר להחליף, לבדוק או לפרוס את השכבה הנמוכה מבלי לגרור איתה גם "
        "את השכבה הגבוהה.",
        "risk_layer_fix": "יש להגדיר את הממשק שהשכבה הנמוכה זקוקה לו בתוך השכבה הנמוכה, "
        "ולתת לשכבה הגבוהה לממש אותו. הקריאה עדיין מתרחשת בזמן ריצה, אך התלות בזמן "
        "הידור מצביעה כעת פנימה.",
        "risk_hub_title": "רכיב עם מספר חיבורים חריג",
        "risk_hub_why": "כל שינוי ברכיב הזה מסכן את שכניו הרבים, ולכן הוא מושך אליו "
        "התנגשויות מיזוג ורגרסיות. ריבוי חיבורים אינו בעיה כשלעצמו, אבל הוא הופך את "
        "הרכיב למקום היקר ביותר בקוד לשינוי.",
        "risk_hub_fix": "יש לבדוק אם החיבורים הם מסוג אחד או מכמה סוגים. אם מכמה סוגים - "
        "לפצל לפי תחומי אחריות. אם מסוג אחד - להציב לפניו ממשק צר כך שהשכנים יהיו תלויים "
        "בחוזה ולא במימוש.",
        "no_issue_title": "לא זוהו בעיות מבניות",
        "no_issue_why": "הניתוח הסטטי לא מצא מעגלי תלות, הפרות שכבות או טיפוסים מנופחים "
        "ברכיבים המוצגים בתרשים הזה.",
        "no_issue_fix": "כדאי לשמר את הגבולות הקיימים ולהריץ את הניתוח מחדש אחרי שינויים "
        "משמעותיים, כדי לזהות נסיגות מוקדם.",
        "evidence_cycle_len": "{length} מודולים משתתפים במעגל",
        "evidence_cycle_path": "מסלול המעגל: {path}",
        "evidence_god_methods": "{methods} מתודות",
        "evidence_god_props": "{properties} שדות או תכונות",
        "evidence_god_deps": "{dependencies} תלויות יוצאות",
        "evidence_hub_degree": "{degree} קשרים נכנסים ויוצאים",
        "evidence_layer_edge": "קשר מסוג '{kind}' מ־{src} אל {dst}",
        "evidence_file": "מוגדר בקובץ {file}",
        "improve_cycle": "לפרק מעגלי תלות באמצעות הוצאת הפשטות משותפות למודול ניטרלי.",
        "improve_god": "לפצל מחלקות גדולות לפי אחריות ולהציג שירותים ממוקדים.",
        "improve_layer": "להוסיף ממשקים כך ששכבות נמוכות לא יפנו לשכבות גבוהות.",
        "improve_abstraction": "להוסיף ממשקים בגבולות המודולים כדי לאפשר החלפה ובדיקות.",
        "improve_docs": "לתעד את האחריות של כל רכיב במאגר הקוד.",
        "strength_layers": "הפרדה ברורה ל־{count} שכבות ארכיטקטוניות.",
        "strength_abstraction": "שימוש בריא בממשקים (יחס הפשטה {ratio}).",
        "strength_nocycle": "אין תלויות מעגליות בין המודולים.",
        "strength_tests": "קיים אזור בדיקות ייעודי במאגר.",
        "strength_containers": "הפריסה מתוארת בצורה הצהרתית ({count} עומסי עבודה).",
        "summary": "המערכת כוללת {components} רכיבים ו־{types} טיפוסים בשפות {languages}. ניתוח סטטי העניק לארכיטקטורה ציון {score}/100 (דירוג {grade}).",
    },
}


def t(language: str, key: str, **kwargs: Any) -> str:
    table = T.get(language, T["en"])
    template = table.get(key) or T["en"].get(key, key)
    try:
        return template.format(**kwargs)
    except (KeyError, IndexError):
        return template


# --------------------------------------------------------------------------- #
# Diagram explanation
# --------------------------------------------------------------------------- #
async def explain_diagram(
    graph: KnowledgeGraph,
    diagram: dict[str, Any],
    language: str = "en",
    provider: AIProvider | None = None,
) -> dict[str, Any]:
    fallback = _explain_fallback(graph, diagram, language)
    if provider is None:
        return fallback
    try:
        context = prompts.graph_summary(graph)
        parsed = await provider.chat_json(
            prompts.explain_diagram(diagram, context, language),
            max_tokens=max(provider.config.max_tokens, 3072),
        )
        parsed.setdefault("purpose", fallback["purpose"])
        parsed.setdefault("description", fallback["description"])
        parsed.setdefault("key_components", fallback["key_components"])
        parsed.setdefault("patterns", fallback["patterns"])
        parsed.setdefault("risks", fallback["risks"])
        parsed.setdefault("improvements", fallback["improvements"])
        parsed["source"] = "ai"
        return parsed
    except AIProviderError as exc:
        log.warning("diagram explanation via AI failed: %s", exc)
        fallback["warning"] = str(exc)
        return fallback


def _explain_fallback(graph: KnowledgeGraph, diagram: dict[str, Any], language: str) -> dict[str, Any]:
    payload = diagram.get("payload") or {}
    nodes = payload.get("nodes") or payload.get("entities") or payload.get("participants") or []
    edges = payload.get("edges") or payload.get("relations") or payload.get("steps") or []
    metrics = (graph.meta or {}).get("metrics", {})

    key_components = [
        {"name": node.get("name", ""), "role": node.get("responsibility") or node.get("kind", "")}
        for node in sorted(nodes, key=lambda n: -(n.get("methods", 0) or 0))[:6]
    ]
    patterns = [
        {"pattern": entry["pattern"], "evidence": entry["evidence"]}
        for entry in (metrics.get("patterns") or [])[:5]
    ]
    risks = _risks(metrics, language)
    improvements = _improvements(metrics, language)

    return {
        "purpose": t(language, f"purpose_{diagram.get('kind', 'architecture')}"),
        "description": t(language, "described", nodes=len(nodes), edges=len(edges))
        + " "
        + t(language, "generated_offline"),
        "key_components": key_components,
        "patterns": patterns,
        "risks": risks,
        "improvements": improvements,
        "source": "static",
    }


def _risk(
    language: str,
    *,
    severity: str,
    kind: str,
    impact: str,
    effort: str,
    issue: str,
    evidence: list[str],
    location: str = "",
) -> dict[str, Any]:
    """Assemble one fully explained risk.

    A severity on its own is not actionable - the reader has no way to tell
    whether "medium" means "rename a variable" or "restructure a package". Every
    risk therefore carries what was measured, why it matters, what it costs and
    what to do about it, so the card can be read without prior context.
    """
    return {
        "severity": severity,
        "severity_label": t(language, f"severity_{severity}"),
        "title": t(language, f"{kind}_title"),
        "issue": issue,
        "why": t(language, f"{kind}_why"),
        "remediation": t(language, f"{kind}_fix"),
        "impact": t(language, f"impact_{impact}"),
        "effort": t(language, f"effort_{effort}"),
        "evidence": [item for item in evidence if item],
        "location": location or "",
    }


def _risks(metrics: dict[str, Any], language: str) -> list[dict[str, Any]]:
    risks: list[dict[str, Any]] = []
    for cycle in (metrics.get("cycles") or [])[:3]:
        modules = list(cycle.get("modules") or [])
        path = " → ".join(modules + modules[:1]) if modules else ""
        risks.append(
            _risk(
                language,
                severity="high",
                kind="risk_cycle",
                impact="coupling",
                effort="large",
                issue=t(language, "risk_cycle", modules=" → ".join(modules)),
                evidence=[
                    t(language, "evidence_cycle_len", length=cycle.get("length", len(modules))),
                    t(language, "evidence_cycle_path", path=path) if path else "",
                ],
            )
        )
    for god in (metrics.get("god_classes") or [])[:3]:
        risks.append(
            _risk(
                language,
                severity="medium",
                kind="risk_god",
                impact="maintainability",
                effort="medium",
                issue=t(language, "risk_god", name=god["name"], methods=god["methods"]),
                evidence=[
                    t(language, "evidence_god_methods", methods=god.get("methods", 0)),
                    t(language, "evidence_god_props", properties=god.get("properties", 0)),
                    t(language, "evidence_god_deps", dependencies=god.get("dependencies", 0)),
                    t(language, "evidence_file", file=god["file"]) if god.get("file") else "",
                ],
                location=god.get("file", ""),
            )
        )
    for violation in (metrics.get("layering_violations") or [])[:3]:
        risks.append(
            _risk(
                language,
                severity="medium",
                kind="risk_layer",
                impact="layering",
                effort="medium",
                issue=t(
                    language,
                    "risk_layer",
                    src=violation["from"],
                    src_layer=violation["from_layer"],
                    dst=violation["to"],
                    dst_layer=violation["to_layer"],
                ),
                evidence=[
                    t(
                        language,
                        "evidence_layer_edge",
                        kind=violation.get("kind", "depends_on"),
                        src=violation["from"],
                        dst=violation["to"],
                    ),
                    t(language, "evidence_file", file=violation["file"]) if violation.get("file") else "",
                ],
                location=violation.get("file", ""),
            )
        )
    for hub in (metrics.get("hubs") or [])[:2]:
        risks.append(
            _risk(
                language,
                severity="low",
                kind="risk_hub",
                impact="change_risk",
                effort="small",
                issue=t(language, "risk_hub", name=hub["name"], degree=hub["degree"]),
                evidence=[
                    t(language, "evidence_hub_degree", degree=hub.get("degree", 0)),
                    t(language, "evidence_file", file=hub["file"]) if hub.get("file") else "",
                ],
                location=hub.get("file", ""),
            )
        )
    if not risks:
        risks.append(
            _risk(
                language,
                severity="low",
                kind="no_issue",
                impact="none",
                effort="none",
                issue=t(language, "no_issue"),
                evidence=[],
            )
        )
    return risks


def _improvements(metrics: dict[str, Any], language: str) -> list[str]:
    improvements: list[str] = []
    if metrics.get("cycles"):
        improvements.append(t(language, "improve_cycle"))
    if metrics.get("god_classes"):
        improvements.append(t(language, "improve_god"))
    if metrics.get("layering_violations"):
        improvements.append(t(language, "improve_layer"))
    if (metrics.get("abstraction_ratio") or 0) < 0.1:
        improvements.append(t(language, "improve_abstraction"))
    if not improvements:
        improvements.append(t(language, "improve_docs"))
    return improvements


# --------------------------------------------------------------------------- #
# Architecture review
# --------------------------------------------------------------------------- #
async def review_architecture(
    graph: KnowledgeGraph,
    metrics: dict[str, Any],
    language: str = "en",
    provider: AIProvider | None = None,
) -> dict[str, Any]:
    fallback = _review_fallback(graph, metrics, language)
    if provider is None:
        return fallback
    try:
        context = prompts.graph_summary(graph, metrics)
        parsed = await provider.chat_json(
            prompts.architecture_review(context, _slim_metrics(metrics), language),
            max_tokens=max(provider.config.max_tokens, 4096),
        )
        parsed["score"] = metrics.get("score", parsed.get("score", 0))
        parsed["grade"] = metrics.get("grade", "")
        parsed.setdefault("strengths", fallback["strengths"])
        parsed.setdefault("issues", fallback["issues"])
        parsed.setdefault("recommendations", fallback["recommendations"])
        parsed["metrics"] = fallback["metrics"]
        parsed["source"] = "ai"
        return parsed
    except AIProviderError as exc:
        log.warning("architecture review via AI failed: %s", exc)
        fallback["warning"] = str(exc)
        return fallback


def _slim_metrics(metrics: dict[str, Any]) -> dict[str, Any]:
    return {
        key: metrics.get(key)
        for key in (
            "score",
            "grade",
            "penalties",
            "abstraction_ratio",
            "module_count",
            "density",
            "average_instability",
            "layers",
            "patterns",
        )
    }


def _review_fallback(graph: KnowledgeGraph, metrics: dict[str, Any], language: str) -> dict[str, Any]:
    stats = graph.stats()
    languages = ", ".join(stats.get("files_by_language", {}).keys()) or "-"
    strengths: list[str] = []
    layers = {k: v for k, v in (metrics.get("layers") or {}).items() if k != "unassigned" and v}
    if len(layers) >= 3:
        strengths.append(t(language, "strength_layers", count=len(layers)))
    if (metrics.get("abstraction_ratio") or 0) >= 0.12:
        strengths.append(t(language, "strength_abstraction", ratio=metrics.get("abstraction_ratio")))
    if not metrics.get("cycles"):
        strengths.append(t(language, "strength_nocycle"))
    if any("test" in (node.module or "").lower() for node in graph.by_kind(NodeKind.FILE)):
        strengths.append(t(language, "strength_tests"))
    containers = len(graph.by_kind(NodeKind.CONTAINER))
    if containers:
        strengths.append(t(language, "strength_containers", count=containers))

    issues = [
        {"severity": risk["severity"], "area": risk.get("impact", ""), "issue": risk["issue"], "evidence": "static analysis"}
        for risk in _risks(metrics, language)
        if risk["issue"] != t(language, "no_issue")
    ]
    recommendations = [
        {"priority": index + 1, "title": item, "detail": item, "effort": "M"}
        for index, item in enumerate(_improvements(metrics, language))
    ]

    return {
        "summary": t(
            language,
            "summary",
            components=len(graph.by_kind(NodeKind.COMPONENT)),
            types=len(graph.by_kind(NodeKind.CLASS, NodeKind.INTERFACE, NodeKind.ABSTRACT_CLASS, NodeKind.STRUCT)),
            languages=languages,
            score=metrics.get("score", 0),
            grade=metrics.get("grade", "-"),
        ),
        "score": metrics.get("score", 0),
        "grade": metrics.get("grade", "-"),
        "strengths": strengths or [t(language, "no_issue")],
        "issues": issues,
        "recommendations": recommendations,
        "quick_wins": _improvements(metrics, language)[:2],
        "metrics": _slim_metrics(metrics),
        "source": "static",
    }


# --------------------------------------------------------------------------- #
# Refactoring
# --------------------------------------------------------------------------- #
async def refactoring_suggestions(
    graph: KnowledgeGraph,
    metrics: dict[str, Any],
    language: str = "en",
    provider: AIProvider | None = None,
) -> dict[str, Any]:
    findings = {
        "cycles": [c["modules"] for c in (metrics.get("cycles") or [])[:8]],
        "god_classes": (metrics.get("god_classes") or [])[:8],
        "layering_violations": (metrics.get("layering_violations") or [])[:8],
        "high_coupling": (metrics.get("coupling") or [])[:8],
        "abstraction_ratio": metrics.get("abstraction_ratio"),
        "orphan_modules": metrics.get("orphan_modules"),
    }
    fallback = _refactor_fallback(findings, language)
    if provider is None:
        return fallback
    try:
        context = prompts.graph_summary(graph, metrics)
        parsed = await provider.chat_json(
            prompts.refactoring_plan(context, findings, language),
            max_tokens=max(provider.config.max_tokens, 4096),
        )
        if not parsed.get("suggestions"):
            fallback["warning"] = "AI returned JSON without refactoring suggestions"
            return fallback
        parsed["source"] = "ai"
        parsed["findings"] = findings
        return parsed
    except AIProviderError as exc:
        log.warning("refactoring plan via AI failed: %s", exc)
        fallback["warning"] = str(exc)
        return fallback


def _refactor_fallback(findings: dict[str, Any], language: str) -> dict[str, Any]:
    suggestions: list[dict[str, Any]] = []
    for cycle in findings["cycles"][:3]:
        suggestions.append(
            {
                "title": t(language, "improve_cycle"),
                "problem": t(language, "risk_cycle", modules=" → ".join(cycle)),
                "approach": t(language, "improve_abstraction"),
                "affected": cycle,
                "impact": "high",
                "effort": "M",
                "steps": [t(language, "improve_cycle"), t(language, "improve_abstraction")],
            }
        )
    for god in findings["god_classes"][:3]:
        suggestions.append(
            {
                "title": t(language, "improve_god"),
                "problem": t(language, "risk_god", name=god["name"], methods=god["methods"]),
                "approach": t(language, "improve_god"),
                "affected": [god["name"]],
                "impact": "medium",
                "effort": "L",
                "steps": [t(language, "improve_god")],
            }
        )
    for violation in findings["layering_violations"][:3]:
        suggestions.append(
            {
                "title": t(language, "improve_layer"),
                "problem": t(
                    language,
                    "risk_layer",
                    src=violation["from"],
                    src_layer=violation["from_layer"],
                    dst=violation["to"],
                    dst_layer=violation["to_layer"],
                ),
                "approach": t(language, "improve_layer"),
                "affected": [violation["from"], violation["to"]],
                "impact": "medium",
                "effort": "M",
                "steps": [t(language, "improve_layer")],
            }
        )
    if not suggestions:
        suggestions.append(
            {
                "title": t(language, "improve_docs"),
                "problem": t(language, "no_issue"),
                "approach": t(language, "improve_docs"),
                "affected": [],
                "impact": "low",
                "effort": "S",
                "steps": [t(language, "improve_docs")],
            }
        )
    return {
        "suggestions": suggestions,
        "target_architecture": t(language, "improve_abstraction"),
        "findings": findings,
        "source": "static",
    }


# --------------------------------------------------------------------------- #
# Natural language diagram requests
# --------------------------------------------------------------------------- #
KIND_KEYWORDS: dict[str, tuple[str, ...]] = {
    "sequence": ("sequence", "flow of", "call flow", "interaction", "login flow", "payment flow", "רצף", "זרימה"),
    "database": ("database", "schema", "er ", "tables", "entity relationship", "בסיס נתונים", "טבלאות"),
    "deployment": ("deploy", "kubernetes", "docker", "infrastructure", "runtime topology", "פריסה", "תשתית"),
    "dependency": ("dependency", "dependencies", "coupling", "circular", "cycle", "תלות", "תלויות"),
    "dataflow": ("data flow", "dataflow", "security boundar", "trust boundar", "privacy", "זרימת נתונים", "אבטחה"),
    "class": ("class", "uml", "inheritance", "types", "מחלקות", "ירושה"),
    "component": ("component", "module view", "boundaries", "interfaces", "רכיבים", "ממשקים"),
    "state": ("state machine", "states", "lifecycle", "status", "מצבים", "מחזור חיים"),
    "architecture": ("architecture", "overview", "high level", "system", "executive", "customer", "ארכיטקטורה", "מערכת"),
}

EXECUTIVE_HINTS = ("executive", "customer", "simplified", "high level", "overview", "מנהלים", "פשוט", "לקוח")
DETAILED_HINTS = ("detailed", "deep", "full", "everything", "מפורט")
# Size adjectives shrink the node budget; they must never become a focus filter.
SIZE_HINTS = {
    "small": 12,
    "tiny": 8,
    "minimal": 10,
    "simple": 14,
    "brief": 12,
    "compact": 14,
    "קטן": 12,
    "פשוט": 14,
}
KIND_STOPWORDS = {
    word
    for keywords in KIND_KEYWORDS.values()
    for keyword in keywords
    for word in keyword.split()
    if len(word) > 2
}
PROMPT_STOPWORDS = {
    "show",
    "create",
    "diagram",
    "only",
    "the",
    "for",
    "with",
    "please",
    "make",
    "view",
    "that",
    "this",
    "need",
    "want",
    "generate",
    "draw",
    "build",
    "architecture",
    "flow",
    "system",
    "customer",
    "facing",
    "simplified",
    "executive",
    "dependencies",
    "small",
    "tiny",
    "minimal",
    "simple",
    "brief",
    "compact",
    "large",
    "full",
    "detailed",
    "deep",
    *KIND_STOPWORDS,
    *SIZE_HINTS,
}


def _focus_matches_graph(graph: KnowledgeGraph, focus: str) -> bool:
    needle = (focus or "").strip().lower()
    if not needle:
        return False
    for node in graph.nodes.values():
        haystack = " ".join(
            [
                node.name or "",
                node.qualified_name or "",
                node.module or "",
                node.file or "",
                str(node.attributes.get("stereotype", "")),
            ]
        ).lower()
        if needle in haystack:
            return True
    return False


def _sanitize_filters(graph: KnowledgeGraph, payload: dict[str, Any]) -> DiagramFilters:
    """Drop focus/module filters that would empty the diagram."""
    filters = DiagramFilters.from_payload(payload)
    if filters.focus and not _focus_matches_graph(graph, filters.focus):
        filters.focus = ""
    if filters.modules:
        known_modules = {
            (node.module or node.qualified_name or node.name or "").lower()
            for node in graph.nodes.values()
        }
        kept = [
            module
            for module in filters.modules
            if any(
                module.lower() == known or known.startswith(f"{module.lower()}/") or module.lower() in known
                for known in known_modules
                if known
            )
        ]
        filters.modules = kept
    return filters


async def interpret_request(
    graph: KnowledgeGraph,
    prompt: str,
    language: str = "en",
    provider: AIProvider | None = None,
) -> dict[str, Any]:
    fallback = _interpret_fallback(graph, prompt)
    if provider is None:
        return fallback
    try:
        available = {
            "components": [node.name for node in graph.by_kind(NodeKind.COMPONENT)][:60],
            "modules": [node.qualified_name for node in graph.by_kind(NodeKind.MODULE)][:80],
            "languages": list(graph.stats().get("files_by_language", {}).keys()),
        }
        parsed = await provider.chat_json(prompts.natural_language_query(prompt, available, language))
        kind = str(parsed.get("kind", "")).strip().lower()
        from app.diagrams.registry import DIAGRAM_KINDS

        if kind not in DIAGRAM_KINDS:
            return fallback
        filters = parsed.get("filters") or {}
        if not isinstance(filters, dict):
            filters = {}
        merged = {**fallback["filters"], **{k: v for k, v in filters.items() if v not in (None, "")}}
        cleaned = _sanitize_filters(graph, merged)
        return {
            "kind": kind,
            "filters": cleaned.to_dict(),
            "title": parsed.get("title") or fallback["title"],
            "reasoning": parsed.get("reasoning") or fallback["reasoning"],
            "source": "ai",
        }
    except AIProviderError as exc:
        log.warning("NL diagram request via AI failed: %s", exc)
        fallback["warning"] = str(exc)
        return fallback


def _interpret_fallback(graph: KnowledgeGraph, prompt: str) -> dict[str, Any]:
    lowered = prompt.lower()
    kind = "architecture"
    for candidate, keywords in KIND_KEYWORDS.items():
        if any(keyword in lowered for keyword in keywords):
            kind = candidate
            break

    detail = "standard"
    if any(hint in lowered for hint in EXECUTIVE_HINTS):
        detail = "executive"
    elif any(hint in lowered for hint in DETAILED_HINTS):
        detail = "detailed"

    max_nodes = 18 if detail == "executive" else 60
    for hint, budget in SIZE_HINTS.items():
        if hint in lowered:
            max_nodes = min(max_nodes, budget)
            if detail == "standard":
                detail = "executive"
            break

    known = {node.name.lower(): node.name for node in graph.by_kind(NodeKind.COMPONENT)}
    known.update(
        {
            (node.qualified_name or node.name).lower(): (node.qualified_name or node.name)
            for node in graph.by_kind(NodeKind.MODULE)
        }
    )
    modules = [original for lowered_name, original in known.items() if lowered_name and lowered_name in lowered]

    focus = ""
    tokens = [token for token in re.split(r"[^A-Za-z0-9_\u0590-\u05FF]+", prompt) if len(token) > 3]
    for token in tokens:
        if token.lower() in PROMPT_STOPWORDS:
            continue
        if token.lower() in known or any(token.lower() in name for name in known):
            focus = token
            break
    # Never invent a focus from leftover prompt adjectives ("small", "class", …);
    # that filters the graph to nothing and surfaces EmptyDiagramError.
    if focus and not _focus_matches_graph(graph, focus):
        focus = ""

    include_external = any(word in lowered for word in ("external", "third party", "integration", "חיצוני"))
    filters = DiagramFilters(
        scope="module" if modules else "project",
        modules=modules[:5],
        include_external=include_external,
        detail=detail,
        focus=focus,
        max_nodes=max_nodes,
    )
    return {
        "kind": kind,
        "filters": filters.to_dict(),
        "title": prompt.strip()[:120],
        "reasoning": "Matched keywords in the request against diagram capabilities.",
        "source": "static",
    }


# --------------------------------------------------------------------------- #
# Comparison + translation
# --------------------------------------------------------------------------- #
async def explain_comparison(
    diff: dict[str, Any], language: str = "en", provider: AIProvider | None = None
) -> dict[str, Any]:
    fallback = {
        "summary": diff.get("summary", ""),
        "impact": diff.get("impact", "low"),
        "highlights": diff.get("highlights", []),
        "risks": diff.get("risks", []),
        "recommendations": [],
        "source": "static",
    }
    if provider is None:
        return fallback
    try:
        parsed = await provider.chat_json(prompts.comparison(diff, language))
        parsed["source"] = "ai"
        return parsed
    except AIProviderError as exc:
        log.warning("comparison explanation via AI failed: %s", exc)
        fallback["warning"] = str(exc)
        return fallback


async def translate(text: str, target: str, provider: AIProvider | None = None) -> dict[str, Any]:
    if provider is None:
        return {"text": text, "translated": False, "reason": "no AI provider configured"}
    try:
        result = await provider.chat(prompts.translation(text, target))
        return {"text": result.strip() or text, "translated": bool(result.strip())}
    except AIProviderError as exc:
        return {"text": text, "translated": False, "reason": str(exc)}
