"""Build the production executable.

Regenerates the icon and the Windows version resource from app/branding.py,
then hands off to PyInstaller. Keeping all three in one command is what stops
the EXE properties dialog from disagreeing with the About page.

    python tools/build_exe.py            # full release build
    python tools/build_exe.py --resources-only   # icon + version resource only

PyInstaller is not a runtime dependency and is deliberately absent from
requirements.txt: it is only needed to package a release. Install it with
`pip install pyinstaller` before the first build.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import make_icon  # noqa: E402

from app import branding  # noqa: E402

BUILD = ROOT / "build"
VERSION_RESOURCE = BUILD / "version_info.txt"

# The structure Windows shows in the file properties dialog. StringFileInfo is
# what Explorer displays; VarFileInfo declares the language (0x0409, US
# English) and the codepage (1200, UTF-16), which must match or the strings are
# silently ignored.
VERSION_TEMPLATE = """# Generated by tools/build_exe.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', {company!r}),
         StringStruct('FileDescription', {description!r}),
         StringStruct('FileVersion', {version!r}),
         StringStruct('InternalName', {product!r}),
         StringStruct('LegalCopyright', {copyright!r}),
         StringStruct('OriginalFilename', {filename!r}),
         StringStruct('ProductName', {product!r}),
         StringStruct('ProductVersion', {version!r})])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_resource() -> Path:
    BUILD.mkdir(parents=True, exist_ok=True)
    VERSION_RESOURCE.write_text(
        VERSION_TEMPLATE.format(
            version_tuple=branding.version_tuple(),
            company=branding.COMPANY,
            description=branding.DESCRIPTION,
            version=branding.VERSION,
            product=branding.PRODUCT_NAME,
            copyright=branding.COPYRIGHT,
            filename=f"{branding.PRODUCT_NAME}.exe",
        ),
        encoding="utf-8",
    )
    return VERSION_RESOURCE


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--resources-only",
        action="store_true",
        help="regenerate the icon and version resource without running PyInstaller",
    )
    parser.add_argument(
        "--target",
        choices=("webview", "native", "both"),
        default="webview",
        help="which front end to build; the two ship side by side",
    )
    args = parser.parse_args()

    icon = make_icon.build()
    resource = write_version_resource()
    print(f"icon:    {icon}")
    print(f"version: {resource}")

    if args.resources_only:
        return 0

    try:
        import PyInstaller  # noqa: F401
    except ImportError:
        print(
            "\nPyInstaller is not installed, so the executable cannot be built here.\n"
            "The icon and version resource above are ready; run:\n"
            "    pip install pyinstaller\n"
            "    python tools/build_exe.py\n",
            file=sys.stderr,
        )
        return 2

    targets = (
        [("ProjectAnalysis.spec", branding.PRODUCT_NAME)]
        if args.target == "webview"
        else [("ProjectAnalysisNative.spec", f"{branding.PRODUCT_NAME}Native")]
        if args.target == "native"
        else [
            ("ProjectAnalysis.spec", branding.PRODUCT_NAME),
            ("ProjectAnalysisNative.spec", f"{branding.PRODUCT_NAME}Native"),
        ]
    )

    for spec, name in targets:
        result = subprocess.run(
            [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", str(ROOT / spec)],
            cwd=ROOT,
            check=False,
        )
        if result.returncode:
            return result.returncode
        produced = ROOT / "dist" / name / f"{name}.exe"
        print(f"\nbuilt: {produced}" if produced.exists() else f"\n{name} finished but the exe is missing")
        if not produced.exists():
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
